### ISSUE TITLE
ID ?

### ISSUE THREAD

**Issue by ricardok1** [Konrud/switch-web-component#1]
Hi there
Should have an ID for control several switches, right?
Thanks

**Comment by Konrud** [comment]
If you want to use several switches on the same page, 
you'll definitely need a unique `id` attribute for each one of them.

**Comment by ricardok1** [comment]
Some example should address this - make it more complete. Good job!

**Comment by Konrud** [comment]
Thank you for your kind words.
I'm not sure what do you mean by "_Some example should address this - make it more complete_"? 

It seems quite obvious, it's like using several `<input type="checkbox">` tags on the page. 
You can of course use them without any `id` attribute if you don't intend to use them in your JS.

**Comment by Konrud** [comment]
note regarding common attributes has been added into documentation
